require 'json'

# 👇 Generic node-based script resolver
def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end
# 👇 Load React Native core and react-native-permissions scripts
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!
#use_modular_headers!



# 👇 Toggle this via ENV var (USE_FRAMEWORKS=static or dynamic)
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# 👇 Your app target
target 'GTPL' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # 👇 Set up required permissions (uncomment what you need)
  setup_permissions([
    'LocationAccuracy',
    'LocationAlways',
    'LocationWhenInUse',
    'Notifications',
    'Camera',
    'MediaLibrary',
    'Microphone',
    'Notifications',
    'PhotoLibrary'
  ])
  
  pod 'FirebaseCore', :modular_headers => true;
  pod 'GoogleUtilities', :modular_headers => true;


  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
